[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "16"
  YARN_VERSION = "1.22.18"

[build]
  base = "packages/@xelah-type-perf-html"
  publish = "styleguide"
  command = "yarn nx build-dev --skip-nx-cache"